import pandas as pd
from pymongo import MongoClient

import pyarrow 
from pymongoarrow.api import Schema
from pymongoarrow.monkey import patch_all
patch_all()
import pymongoarrow as pma

from bson.objectid import ObjectId
from datetime import datetime as dt
from sklearn.preprocessing import LabelEncoder

from .wyscout_metadata_handler import get_players_maps

# get mapping of playerId's to player positions
_, _, player_to_pos, _ = get_players_maps(verbose = False)

# encode position strings as integers. We don't use one-hot encoding because torch.nn.CrossEntropyLoss expects numerical labels
wyscout_pos_to_num = {'GK': 0, 'DF': 1, 'MD': 2, 'FW': 3}

competition_to_wyId = {
    'England': 364,
    'European_Championship': 102,
    'France': 412,
    "Germany": 426,
    "Italy": 524,
    "Spain": 795,
    "World_Cup": 28,
}

def get_full_events_df(competitions: list = None):
    """
    Merges event dataframes of all 7 competitions in Wyscout dataset.
    """
    full_events_df = None
    
    valid_competitions = {'England', 'European_Championship', 'France', 'Germany', 'Italy', 'Spain', 'World_Cup'}
    
    if competitions is None:
        competitions = list(valid_competitions)
    
    if type(competitions) != list:
        competitions = [competitions]

    for competition in competitions:
        assert competition in valid_competitions, f'{competition} is not a recognized competition'

    
    for competition in competitions:
        current_client = CompetitionClient("mongodb://localhost:27017/", competition)
        if (full_events_df is None):
            full_events_df = current_client.events_df
        else:
            full_events_df = pd.concat([full_events_df, current_client.events_df], ignore_index = True)
    return full_events_df

class CompetitionClient:
    """
    PyMongo client wrapper designed to store data specific to a given competitioj
    """
    def __init__(self, connection_string: str, competition_string: str):
        """
        Initializes MongoDB client and calls _startup() to get competition-specific data.
        params:
            connection_string: connection string generated by MongoDB
            competition_string: a string in the set {"England", "European_Championship", "France", "Germany", "Italy", "Spain", "World_Cup"}
        """
        # MongoDB Client
        self._client = MongoClient(connection_string)
        
        # delegates other initialization steps to _startup method. This allows for switching of competitions
        self._startup(competition_string)
        
    def _startup(self, competition_string):
        """
        Retrieves competition-specific data, including events, match data, and competition details.
        """
        # Reference to events collection specific to chosen competition 
        self.events = self._client['soccer_events'][f'events_{competition_string}']
        
        # Reference to matches collection specific to chosen competition
        self.matches = self._client['soccer_events'][f'matches_{competition_string}']
        
        # Reference to metadata database
        self.metadata = self._client['soccer_events_metadata']
        
        # String holding competition name
        self.competition_string = competition_string

        # wyId of competition as assigned by Wyscout API
        self._competition_wyId = competition_to_wyId[competition_string]

        # Initializes competition details
        self._details = self.metadata['competitions'].find_one({'wyId': self._competition_wyId},
                                                               {'_id': 0})

        # Record events and matches data. 
        # Initializes self.events_df and self.match_details
        self._init_match_events_df()
        self._init_match_details()

    def switch_competitions(self, competition_string):
        """
        Switches current competition by calling _startup() to get competition-specific data for the 
        new specified competition
        """
        self._startup(competition_string)

    def __str__(self):         
        output = f"""Competition Details
        Competition: {self._details['name']}
        Format: {self._details['format']}
        Type: {self._details['type']}
        Area: {self._details['area']['name']}
        """
        return output

    def _init_match_events_df(self):  
        """
        Loads all events data from given competition
        """      
        df = self.events.find_pandas_all({}).drop('_id', axis = 1)
        df['tags'] = df['tags'].apply(lambda x: [e['id'] for e in x])
        self.events_df = df

    def _init_match_details(self):
        """
        Loads and processes data on all matches in given competition
        """
        result = self.matches.aggregate([
            {                               # convert teamsData document into an array of 2 documents representing the 2 teams
                '$project': {'_id': 0, 
                            'wyId': 1,
                            'label': 1,
                            'date': 1,
                            'winner': 1,
                            'dateutc': 1,
                            'teamsData': {'$objectToArray': '$teamsData'}}
            },
            {                               # separate teamsData into 2 fields: team1_players and team2_players
                '$project': {
                    'label': 1,
                    'date': 1,
                    'wyId': 1,
                    'winner': 1,
                    'dateutc': 1,
                    'team1_players': {'$arrayElemAt': ['$teamsData.v', 0]},
                    'team2_players': {'$arrayElemAt': ['$teamsData.v', 1]}
                }
            },
            {                               # get team ids and merge bench + lineup
                '$set': {
                    'team1_id': '$team1_players.teamId',
                    'team2_id': '$team2_players.teamId',
                    'team1_players': {
                        '$concatArrays': ['$team1_players.formation.lineup']
                    },
                    'team2_players': {
                        '$concatArrays': ['$team2_players.formation.lineup']
                    }
                }
            },
            {                               # get playerId's
                '$project': {
                    'wyId': 1,
                    'label': 1,
                    'winner': 1,
                    'date': 1,
                    'dateutc': 1,
                    'team1_id': 1, 
                    'team2_id': 1,
                    'team1_players': {
                        '$map':{
                            'input': '$team1_players',
                            'as': 'player',
                            'in': '$$player.playerId'
                        }
                    },
                    'team2_players': {
                        '$map':{
                            'input': '$team2_players',
                            'as': 'player',
                            'in': '$$player.playerId'
                        }
                    }
                }
            }
        ])
        result = list(result)
        keys = ['date', 'dateutc', 'label', 'winner', 'team1_id', 'team1_players', 'team2_id', 'team2_players']
        result = {e['wyId']: {key: e[key] for key in keys} for e in result}
        self.match_details = result

class MatchData:
    """
    Class storing data specific to a given match.
    """
    def __init__(self, client: CompetitionClient, match_id: int):
        """
        Initializes instance using a CompetitionClient and match wyId.
        params:
            client: a CompetitionClient instance set to the appropriate competition hosting the desired match.
            match_id: an integer representing the match's Wyscout match id.
        """
        # record client by which data is retrieved
        self._client = client
        
        # record match wyId 
        self.match_id = match_id

        # get events and details specific to match
        self.events_df = self._client.events_df[self._client.events_df['matchId'] == match_id]
        self.details = self._client.match_details[match_id]

        # unpack match details
        self.winner = self.details['winner']
        self.team1 = self.details['team1_id']
        self.team2 = self.details['team2_id']
        self.team1_players = self.details['team1_players']
        self.team2_players = self.details['team2_players']
        self.team1_positions = [wyscout_pos_to_num[player_to_pos[player]] for player in self.team1_players]
        self.team2_positions = [wyscout_pos_to_num[player_to_pos[player]] for player in self.team2_players]

        # sort (used for indexing dataframes)
        self.team1_players.sort()  
        self.team2_players.sort()
        
        self.team1_encoder = LabelEncoder().fit(self.team1_players)
        self.team2_encoder = LabelEncoder().fit(self.team2_players)

    def __str__(self):
        output = f'Match Details\n\t{self.details['label']}\n\t{self.details['date']}'
        return output

    def get_match_details(self):
        """
        Returns details specific to given match.
        """
        return self.details

    def get_match_events_df(self):
        """
        Returns events specific to given match.
        """
        return self.events_df


